//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSAPPEntities : DbContext
    {
        public CMSAPPEntities()
            : base("name=CMSAPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMPANY> COMPANies { get; set; }
        public virtual DbSet<FEATURE> FEATURES { get; set; }
        public virtual DbSet<MENU> MENUs { get; set; }
        public virtual DbSet<USERLOGIN> USERLOGINs { get; set; }
    }
}
