//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public int ID { get; set; }
        public string COMP_NAME { get; set; }
        public string COMP_TITLE { get; set; }
        public string COMP_ADDRESS { get; set; }
        public string COMP_BANNER { get; set; }
        public Nullable<System.DateTime> DATE_EVENT { get; set; }
        public string ABOUTUS1 { get; set; }
        public string ABOUTUS2 { get; set; }
    }
}
