//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEATURE
    {
        public int ID { get; set; }
        public string FEATURE_NAME { get; set; }
        public string FEATURE_PATH { get; set; }
        public Nullable<int> SEQ { get; set; }
    }
}
